### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by hf-lopes**
### Status
**READY**

### Background context
On fklearn open source announcement meetup we did a live presentation about how to use fklearn

### Description of the changes proposed in the pull request
Adding two notebooks:
* Notebook used to generate the dataset that was used on the presentation
* Notebook of the presentation with all the analyses/models done on top of the dataset

### Where should the reviewer start?
Review both notebooks

### CODE REVIEW

**Comment by caique-lima** [comment]
> I think it's better to move this tutorials to the docs folder, and link them to the documentation, just like this one https://github.com/nubank/fklearn/blob/master/docs/source/examples/causal_inference.ipynb

@hf-lopes can you do this change?

**Comment by mauricionr** [comment]
The meetup was Recorded?

**Comment by caique-lima** [comment]
> The meetup was Recorded?

Yep, soon we'll release the videos from this presentation

**Comment by hf-lopes** [comment]
Sorry for the delay, just moved the files!

**Pull request merged**
