### PR TITLE
Flexibilize dependencies, as of 2020-07

### PR DESCRIPTION
**Pull request by vitorsrg**
### Status
**READY**

### Background context
Some of the bounds are more than a year old already.

### CODE REVIEW

**Comment by caique-lima** [comment]
Just saw that parso was changed to keep compatibility with jedi

**Comment by caique-lima** [comment]
Regarding numba https://github.com/nubank/fklearn/pull/139

> numba to keep compatibility with the previous api with numba.errors module

I think with previous requirements some of them used numba.errors, probably fixed with more flexible requirements

**Comment by vitorsrg** [comment]
The plan was to allow newer versions of numpy, pandas and sklearn.

For cloudpickle and joblib, I guess I'll change them back, then.

I didn't remove numba, but it seams I I accidentally sorted the file somehow

**Comment by vitorsrg** [comment]
> Do we have a reason to change cloudpickle? historically it's been an issue to deal with different versions.

Doesn't bumping minor justify breaking pickles from previous versions?

**Comment by caique-lima** [comment]
> Doesn't bumping minor justify breaking pickles from previous versions?

Sadly, yes. As we still uses the 0 major versions, things break all the time.

We can create a milestone for Fklearn 2 and put cloudpickle 1 as one of the tasks, this will probably make everything more stable. We also can start to support only Pandas >= 1, <2. We can take a look at things we should deprecate, and break and put everything in the same release

**Pull request merged**
